version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: leptos_frontend
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rust_backend
    restart: always
    # コマンドを明示的に指定
    command: ./backend
    environment:
      - RUST_LOG=info
    ports:
      - "4000:4000"

  nginx:
    image: nginx:alpine
    container_name: nginx_gateway
    restart: always
    ports:
      - "80:80"
    volumes:
      # ./frontend/dist:/usr/share/nginx/html の代わりに
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
